import jsPDF from 'jspdf'
import { ReportData } from '@/types'

export function generateReportPDF(
  reportData: ReportData,
  reportId: string,
  patientInfo: { name?: string; age?: number; dob?: string; sex?: string; language: string; visitType: string; knownConditions?: string },
  hospitalName?: string,
  physicianNotes?: string,
): jsPDF {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 20
  const contentWidth = pageWidth - margin * 2
  let y = 0

  const darkGreen = [26, 61, 43] as [number, number, number]
  const amber = [244, 165, 53] as [number, number, number]
  const white = [255, 255, 255] as [number, number, number]
  const lightSurface = [237, 250, 244] as [number, number, number]
  const textColor = [15, 36, 25] as [number, number, number]
  const mutedText = [100, 130, 110] as [number, number, number]

  function addHeader() {
    doc.setFillColor(...darkGreen)
    doc.rect(0, 0, pageWidth, 28, 'F')
    doc.setTextColor(...white)
    doc.setFontSize(18)
    doc.setFont('helvetica', 'bold')
    doc.text('KEIRO HEALTH REPORT', margin, 12)
    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    doc.text('Generated by Kai - AI-assisted intake for clinician review', margin, 19)
    const dateStr = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
    doc.text(dateStr, pageWidth - margin, 12, { align: 'right' })
    doc.text(`Report ID: ${reportId}`, pageWidth - margin, 19, { align: 'right' })
    y = 36
  }

  function addSectionHeader(title: string) {
    checkPageBreak(12)
    doc.setFillColor(...darkGreen)
    doc.rect(margin, y, contentWidth, 8, 'F')
    doc.setTextColor(...white)
    doc.setFontSize(9)
    doc.setFont('helvetica', 'bold')
    doc.text(title.toUpperCase(), margin + 3, y + 5.5)
    y += 12
    doc.setTextColor(...textColor)
  }

  function addRow(label: string, value: string, indent = 0) {
    checkPageBreak(7)
    doc.setFontSize(8.5)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...mutedText)
    doc.text(label, margin + indent, y)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...textColor)
    const lines = doc.splitTextToSize(value || '—', contentWidth - 45 - indent)
    doc.text(lines, margin + 45 + indent, y)
    y += lines.length * 5.5 + 1.5
  }

  function addText(text: string, indent = 0) {
    checkPageBreak(7)
    doc.setFontSize(8.5)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...textColor)
    const lines = doc.splitTextToSize(text, contentWidth - indent)
    doc.text(lines, margin + indent, y)
    y += lines.length * 5.5 + 1.5
  }

  function checkPageBreak(needed = 20) {
    if (y + needed > doc.internal.pageSize.getHeight() - 25) {
      doc.addPage()
      y = 20
    }
  }

  function addPageFooter() {
    const pageHeight = doc.internal.pageSize.getHeight()
    doc.setFillColor(...darkGreen)
    doc.rect(0, pageHeight - 12, pageWidth, 12, 'F')
    doc.setTextColor(...white)
    doc.setFontSize(7.5)
    doc.setFont('helvetica', 'normal')
    const footerText = hospitalName
      ? `Generated by Kai for Keiro - Not a medical diagnosis - Report ID: ${reportId} - ${hospitalName}`
      : `Generated by Kai for Keiro - Not a medical diagnosis - Report ID: ${reportId}`
    doc.text(footerText, pageWidth / 2, pageHeight - 4.5, { align: 'center' })
  }

  // Build the PDF
  addHeader()

  // Patient Summary
  addSectionHeader('Patient Summary')
  addRow('Name', patientInfo.name || 'Not provided')
  addRow('Date of Birth', patientInfo.dob || 'Not provided')
  addRow('Age', patientInfo.age ? `${patientInfo.age} years` : 'Not provided')
  addRow('Sex', patientInfo.sex || 'Not provided')
  if (patientInfo.knownConditions) addRow('Known Conditions', patientInfo.knownConditions)
  addRow('Patient Language', patientInfo.language)
  addRow('Report Language', 'English')
  addRow('Visit Type', patientInfo.visitType)
  addRow('Report Generated', new Date().toLocaleString())
  y += 4

  // Chief complaint
  addSectionHeader('Chief Complaint')
  addText(reportData.chief_complaint || '—')
  y += 4

  if (reportData.clinical_symptoms_summary && reportData.clinical_symptoms_summary !== 'Not reported') {
    addSectionHeader('Clinical Symptom Summary')
    addText(reportData.clinical_symptoms_summary)
    y += 4
  }

  // Symptoms
  if (reportData.symptoms?.length > 0) {
    addSectionHeader('Symptoms - Detailed')
    reportData.symptoms.forEach((s, i) => {
      if (i > 0) y += 2
      doc.setFontSize(8.5)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(...darkGreen)
      checkPageBreak(8)
      doc.text(`Symptom ${i + 1}`, margin + 2, y)
      y += 5.5
      doc.setTextColor(...textColor)
      if (s.location) addRow('Location', s.location, 4)
      if (s.severity) addRow('Severity', `${s.severity}/10`, 4)
      if (s.duration) addRow('Duration', s.duration, 4)
      if (s.character) addRow('Character', s.character, 4)
      if (s.onset) addRow('Onset', s.onset, 4)
      if (s.modifiers) addRow('Modifiers', s.modifiers, 4)
    })
    y += 4
  }

  // Associated symptoms
  if (reportData.associated_symptoms) {
    addSectionHeader('Associated Symptoms')
    const as = reportData.associated_symptoms
    const present: string[] = []
    const absent: string[] = []
    if (as.fever !== undefined) (as.fever ? present : absent).push('Fever')
    if (as.nausea !== undefined) (as.nausea ? present : absent).push('Nausea/Vomiting')
    if (as.fatigue !== undefined) (as.fatigue ? present : absent).push('Fatigue')
    if (as.dizziness !== undefined) (as.dizziness ? present : absent).push('Dizziness')
    if (as.appetite_loss !== undefined) (as.appetite_loss ? present : absent).push('Appetite Loss')
    if (present.length) addRow('Present', present.join(', '))
    if (absent.length) addRow('Denied', absent.join(', '))
    y += 4
  }

  // Lifestyle
  if (reportData.lifestyle) {
    addSectionHeader('Lifestyle Notes')
    const ls = reportData.lifestyle
    if (ls.smoker !== undefined) addRow('Tobacco Use', ls.smoker ? 'Yes' : 'No')
    if (ls.alcohol !== undefined) addRow('Alcohol Use', ls.alcohol ? 'Yes' : 'No')
    if (ls.recent_travel !== undefined) addRow('Recent Travel', ls.recent_travel ? 'Yes' : 'No')
    y += 4
  }

  // Medications
  if (reportData.medications?.length > 0) {
    addSectionHeader('Current Medications')
    reportData.medications.forEach(m => {
      addRow(m.name, `${m.dosage || '—'} - ${m.frequency || '—'}`)
    })
    y += 4
  }

  // Conditions & History
  addSectionHeader('Known Conditions & History')
  if (reportData.conditions?.length > 0) {
    addRow('Conditions', reportData.conditions.join(', '))
  } else {
    addRow('Conditions', 'None reported')
  }
  if (reportData.history) addRow('History', reportData.history)
  y += 4

  // Family History
  if (reportData.family_history) {
    addSectionHeader('Family History')
    addText(reportData.family_history)
    y += 4
  }

  // Allergies
  addSectionHeader('Allergies')
  addText(reportData.allergies?.length > 0 ? reportData.allergies.join(', ') : 'No known allergies')
  y += 4

  // Possible Differentials
  if (reportData.possible_conditions?.length > 0) {
    addSectionHeader('Possible Differentials — Physician Reference')
    doc.setFillColor(255, 248, 225)
    doc.setDrawColor(...amber)
    checkPageBreak(10)
    doc.roundedRect(margin, y - 2, contentWidth, 8, 2, 2, 'FD')
    doc.setFontSize(7.5)
    doc.setFont('helvetica', 'italic')
    doc.setTextColor(120, 80, 10)
    doc.text('For physician reference only - not a diagnosis', margin + 3, y + 3.5)
    y += 10
    reportData.possible_conditions.forEach((pc, i) => {
      checkPageBreak(12)
      doc.setFontSize(8.5)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(...darkGreen)
      doc.text(`${i + 1}. ${pc.condition}`, margin + 2, y)
      y += 5.5
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(...textColor)
      const lines = doc.splitTextToSize(pc.reasoning, contentWidth - 8)
      doc.text(lines, margin + 6, y)
      y += lines.length * 5 + 3
    })
    y += 2
  }

  // Disclaimer
  checkPageBreak(36)
  doc.setFillColor(255, 245, 220)
  doc.setDrawColor(...amber)
  doc.roundedRect(margin, y, contentWidth, 32, 3, 3, 'FD')
  doc.setFontSize(8.5)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(120, 80, 10)
  doc.text('AI-GENERATED INTAKE SUMMARY', margin + 4, y + 7)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7.5)
  const disclaimer = [
    'This report was generated from a patient conversation to assist communication only.',
    'It does not constitute medical advice, clinical assessment, or diagnosis.',
    'All information must be verified directly with the patient by a licensed physician.',
    'Keiro is not a medical provider.',
  ]
  disclaimer.forEach((line, i) => {
    doc.text(line, margin + 4, y + 13 + i * 5)
  })
  y += 38

  // Physician Notes
  doc.addPage()
  y = 20
  addSectionHeader('Physician Notes')
  if (physicianNotes?.trim()) {
    addText(physicianNotes.trim())
    y += 4
  } else {
    doc.setFillColor(...lightSurface)
    doc.rect(margin, y, contentWidth, 80, 'F')
    for (let lineY = y + 10; lineY < y + 80; lineY += 10) {
      doc.setDrawColor(197, 237, 216)
      doc.line(margin + 4, lineY, margin + contentWidth - 4, lineY)
    }
    y += 86
  }

  // Add footer to all pages
  const totalPages = doc.getNumberOfPages()
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p)
    addPageFooter()
  }

  return doc
}