'use client'

import { motion } from 'framer-motion'
import Link from 'next/link'
import { ArrowLeft } from 'lucide-react'

export default function TermsPage() {
  return (
    <motion.div
      initial={{ opacity: 0, y: 16 }}
      animate={{ opacity: 1, y: 0 }}
      className="flex flex-col min-h-screen"
      style={{ maxWidth: 640, margin: '0 auto', background: 'white' }}
    >
      <div className="flex items-center gap-3 px-6 py-4 sticky top-0 z-10" style={{ background: 'white', borderBottom: '1px solid #c5edd8' }}>
        <Link href="/" className="w-8 h-8 rounded-lg flex items-center justify-center" style={{ background: '#f8fffe' }}>
          <ArrowLeft size={16} style={{ color: '#1a3d2b' }} />
        </Link>
        <h1 className="font-bold text-base" style={{ color: '#0f2419' }}>Terms of Service</h1>
      </div>

      <div className="px-6 py-8">
        <div className="text-xs mb-8" style={{ color: '#3B6D11' }}>Last updated: January 2026</div>

        {[
          {
            title: '1. What Keiro Is',
            content: 'Keiro is a free medical intake communication tool. It helps non-English speaking patients describe their symptoms to a doctor by facilitating a conversation in their native language and generating a summary report in English. Keiro is NOT a medical device, healthcare provider, or medical advisory service.'
          },
          {
            title: '2. Not Medical Advice',
            content: 'The content generated by Keiro, including all AI-generated summaries, possible conditions lists, and reports, does not constitute medical advice, diagnosis, or treatment recommendations. Always seek the advice of your physician or other qualified health provider with questions you may have regarding a medical condition.'
          },
          {
            title: '3. Emergency Situations',
            content: 'Keiro is not an emergency service. In any emergency, call 911 immediately. Keiro provides an emergency screen with basic multilingual emergency phrases as a courtesy, but you must call emergency services directly.'
          },
          {
            title: '4. Free Forever',
            content: 'Keiro is and will always be free for patients. We commit to never charging patients for core functionality, never placing patient communications behind a paywall, and never showing advertisements in the patient-facing app.'
          },
          {
            title: '5. Accuracy',
            content: 'While we strive for accuracy, AI-generated medical summaries may contain errors. All information in generated reports must be verified by a licensed physician. Do not make medical decisions based solely on Keiro-generated content.'
          },
          {
            title: '6. Your Responsibility',
            content: 'You are responsible for providing accurate information to Kai. The quality of the generated report depends on the accuracy of information you provide. You are responsible for presenting the report to your healthcare provider and discussing it with them directly.'
          },
          {
            title: '7. Acceptable Use',
            content: 'You agree not to use Keiro to submit false or misleading medical information, attempt to extract harmful information or circumvent safety guidelines, share your account credentials with others, or use the service for any illegal purpose.'
          },
          {
            title: '8. Changes to Terms',
            content: 'We may update these terms. Continued use after changes constitutes acceptance. We will notify users of material changes via the app.'
          },
          {
            title: '9. Contact',
            content: 'Questions about these terms? Contact us at keiro.contact@gmail.com.'
          },
        ].map((section, i) => (
          <div key={i} className="mb-8">
            <h2 className="text-base font-bold mb-3" style={{ color: '#1a3d2b' }}>{section.title}</h2>
            <p className="text-sm leading-relaxed" style={{ color: '#3B6D11' }}>{section.content}</p>
          </div>
        ))}

        <div className="mt-8 pt-6 border-t" style={{ borderColor: '#c5edd8' }}>
          <p className="text-xs text-center" style={{ color: '#3B6D11' }}>
            <Link href="/privacy" className="underline">Privacy Policy</Link>
            {' · '}
            Keiro · Free forever
          </p>
        </div>
      </div>
    </motion.div>
  )
}
