'use client'

import { motion } from 'framer-motion'
import Link from 'next/link'
import { ArrowLeft } from 'lucide-react'

const LAST_UPDATED = 'June 7, 2026'

export default function TermsPage() {
  return (
    <motion.div
      initial={{ opacity: 0, y: 16 }}
      animate={{ opacity: 1, y: 0 }}
      className="flex flex-col min-h-svh"
      style={{ maxWidth: 640, margin: '0 auto', background: 'white' }}
    >
      <header className="flex items-center gap-3 px-6 py-4 sticky top-0 z-10" style={{ background: 'white', borderBottom: '1px solid var(--border-subtle)' }}>
        <Link
          href="/"
          aria-label="Back to home"
          className="w-11 h-11 rounded-lg flex items-center justify-center"
          style={{ background: 'var(--brand-subtle)' }}
        >
          <ArrowLeft size={16} aria-hidden="true" style={{ color: 'var(--brand-ink)' }} />
        </Link>
        <h1 className="font-bold text-base" style={{ color: 'var(--text-primary)' }}>Terms of Use</h1>
      </header>

      {/* main#main-content on every page: it is the skip-link target from the
          root layout, and screen-reader users navigate by landmark. */}
      <main id="main-content" className="px-6 py-8">
        <div className="text-xs mb-8" style={{ color: 'var(--text-secondary)' }}>Last updated: {LAST_UPDATED}</div>

        <Section title="1. What Keiro Is">
          <p>
            Keiro is a free multilingual medical intake communication tool. It helps
            non-English-speaking patients describe their symptoms to a healthcare provider by
            facilitating a real-time conversation in their native language and generating a
            structured summary report in English.
          </p>
          <p>
            <strong>Keiro is NOT a medical device, healthcare provider, medical advisory service,
            or licensed interpreter service.</strong> Keiro is a communication aid only.
          </p>
        </Section>

        <Section title="2. Not Medical Advice">
          <p>
            The content generated by Keiro — including all AI-generated summaries, symptom
            descriptions, possible condition lists, and reports — <strong>does not constitute
            medical advice, diagnosis, or treatment recommendations</strong>. Always seek the
            advice of your physician or other qualified health provider with any questions you
            have regarding a medical condition. Never disregard professional medical advice or
            delay seeking it because of something Keiro produced.
          </p>
        </Section>

        <Section title="3. AI-Generated Content">
          <p>
            <strong>Responses are generated by an AI assistant and may not be accurate. Always
            confirm important information with your doctor.</strong> AI language models can make
            errors, misunderstand context, or produce plausible-sounding but incorrect output.
            All information in generated reports must be verified by a licensed physician directly
            with the patient. Do not make medical decisions based solely on Keiro-generated content.
          </p>
        </Section>

        <Section title="4. Your Health Information">
          <p>
            <strong>Conversations with Kai are processed in real time and never saved.</strong>{' '}
            If you use Keiro as a guest, nothing about you is stored, and your report exists only
            in your browser tab until you close it.
          </p>
          <p>
            If you sign in, the structured reports Kai prepares are stored to your account — with
            your explicit consent — so you can access them later. They are encrypted, visible only
            to you, and deletable at any time in Settings. See our{' '}
            <Link href="/privacy" className="underline" style={{ color: 'var(--brand-ink)' }}>
              Privacy Policy
            </Link>{' '}
            for full details.
          </p>
        </Section>

        <Section title="5. HIPAA Disclaimer">
          <p>
            Keiro is a communication aid tool, not a covered entity under HIPAA. Keiro does not
            handle Protected Health Information (PHI) as defined by HIPAA. HIPAA obligations for
            patient data reside with the healthcare provider who uses Keiro in their clinical
            workflow, not with Keiro. Patients and providers should not use Keiro as a substitute
            for HIPAA-compliant communication or record-keeping systems.
          </p>
        </Section>

        <Section title="6. Emergency Situations">
          <p>
            <strong>Keiro is not an emergency service.</strong> In any emergency, call your local
            emergency number immediately. Keiro provides a multilingual emergency phrase screen as a communication
            courtesy, but you must contact emergency services directly. Do not rely on Keiro
            during a medical emergency.
          </p>
        </Section>

        <Section title="7. Use in Clinical Settings — Minor Users">
          <p>
            Keiro is intended for use in clinical settings under the supervision of a licensed
            healthcare provider. <strong>Keiro is not directed at children under 13.</strong> If a
            minor patient requires assistance, a parent, guardian, or healthcare professional must
            operate the app on their behalf. By using Keiro on behalf of a minor, you represent
            that you are the minor&apos;s legal guardian or a licensed healthcare professional
            acting in a clinical capacity.
          </p>
        </Section>

        <Section title="8. Free Forever">
          <p>
            Keiro is and will always be free for patients. We commit to never charging patients for
            core functionality, never placing patient communications behind a paywall, and never
            showing advertisements in the patient-facing app.
          </p>
        </Section>

        <Section title="9. Accuracy and Your Responsibility">
          <p>
            You are responsible for providing accurate information to Kai. The quality of the
            generated report depends on the accuracy of the information you provide. You are
            responsible for presenting the report to your healthcare provider and discussing it
            with them directly. Keiro cannot be held liable for clinical decisions made on the
            basis of inaccurate patient-provided information.
          </p>
        </Section>

        <Section title="10. Acceptable Use">
          <p>You agree not to use Keiro to:</p>
          <ul>
            <li>Submit false or misleading medical information.</li>
            <li>Attempt to extract harmful information or circumvent safety guidelines.</li>
            <li>Share your account credentials with others.</li>
            <li>Use the service for any unlawful purpose.</li>
            <li>Reverse-engineer or scrape Keiro&apos;s AI responses at scale.</li>
          </ul>
        </Section>

        <Section title="11. Limitation of Liability">
          <p>
            To the fullest extent permitted by applicable law, Keiro and its operators shall not be
            liable for any clinical outcomes, missed diagnoses, treatment decisions, or patient harm
            arising from the use or misuse of Keiro-generated content. Keiro is provided &quot;as
            is&quot; without warranties of any kind, express or implied.
          </p>
        </Section>

        <Section title="12. Changes to These Terms">
          <p>
            We may update these terms. Continued use of Keiro after changes are posted constitutes
            acceptance of the revised terms. We will notify signed-in users of material changes
            via the app. The &quot;Last updated&quot; date at the top of this page reflects the
            most recent revision.
          </p>
        </Section>

        <Section title="13. Contact">
          <p>
            Questions about these terms? Contact us at:{' '}
            {/* Underlined: colour alone can't mark a link inside body text (WCAG 1.4.1) */}
            <a
              href="mailto:keiro.contact@gmail.com"
              className="underline"
              style={{ color: 'var(--brand-ink)' }}
              rel="noopener noreferrer"
            >
              keiro.contact@gmail.com
            </a>
          </p>
        </Section>

        <div className="mt-8 pt-6 border-t" style={{ borderColor: 'var(--border-subtle)' }}>
          <p className="text-xs text-center" style={{ color: 'var(--text-secondary)' }}>
            <Link href="/privacy" className="underline">Privacy Policy</Link>
            {' · '}
            Keiro · Free forever
          </p>
        </div>
      </main>
    </motion.div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mb-8">
      <h2 className="text-base font-bold mb-3" style={{ color: 'var(--brand-ink)' }}>{title}</h2>
      <div className="text-sm leading-relaxed space-y-3" style={{ color: 'var(--text-secondary)' }}>
        {children}
      </div>
    </div>
  )
}